# Site settings
title: Enrico Tranquillini  
email:  
description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://iltranqui.github.io"
twitter_username: iltranqui
github_username:  iltranqui

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
